[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mbb"
version = "0.0.6"

dependencies = [
"matplotlib",
"astropy",
"numpy",
"scipy",
"emcee",
"corner"
]