[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mbb"
version = "0.4.0"
readme = "README.md"

dependencies = [
"matplotlib",
"astropy",
"numpy",
"scipy",
"emcee",
"corner",
"tqdm"
]